### ISSUE TITLE
sudo support?

### ISSUE THREAD

**Issue by roachsinai** [mananapr/cfiles#22]
Could you please add exec command like `y`, `v` in administer?

**Comment by mananapr** [comment]
running `sudo cfiles` should allow you to copy and move files to directories that require root access. is this what you want or did i misinterpret your question?

**Comment by roachsinai** [comment]
I got problem when copy files to dirs like `/usr/share` which need high authority. And found that `sudo cfiles` and `cfiles` don't share the same `selection list`, so I couldn't goto `/usr/share`  dir then `sudo cfiles` press `y` to copy files here, cause the `selection list` right now is empty.

**Comment by mananapr** [comment]
ah I see. `cfiles` finds the `XDG_CACHE_DIR` variable of the user that has started the `cfiles` process. (If that is not found it uses $HOME/.cache/cfiles folder). So the location will be different for `sudo cfiles` and `cfiles`. I don't think there is any option other than running two `sudo cfiles` instances rather than one `cfiles` and one `sudo cfiles` instance in case you want to copy/move/remove files to/from privileged directories. 

Other way could be to add alternate keybindings for commands that use `sudo`. So for example, `y` for `cp` and `Y` for `sudo cp`. What do you think about this approach?

**Comment by mananapr** [comment]
alternative you can add a user script in the scripts folder that runs the `sudo cp` command for all the files listed in `/home/root/.cache/cfiles/clipboard`

**Comment by roachsinai** [comment]
In my opinion, `Y` for `sudo cp` is better.

**Comment by mananapr** [comment]
instead of adding new keybindings I am thinking of detecting if the user has permissions to do the task or not and automatically use `sudo` in that case. This approach seems cleaner to me. I'll add this in the next commit

**Comment by mananapr** [comment]
I have made the relevant changes in the latest commit. Let me know if everything works as expected.

**Comment by roachsinai** [comment]
I updated local PKGBUILD file, worked, thanks a lot.
