### ISSUE TITLE
pdf previews are broken

### ISSUE THREAD

**Issue by yurivict** [mananapr/cfiles#40]
This line:
> execlp("/usr/local/bin/pdftoppm","/usr/local/bin/pdftoppm","-l","1","-jpeg",filepath,"-singlefile", "/tmp/prev", (char *)NULL);

translates into this command:
> /usr/local/bin/pdftoppm x.pdf  -l 1 -jpeg . -singlefile /tmp/prev

which fails and shows the usage message:
> Usage: pdftoppm [options] [PDF-file [PPM-file-prefix]]

```
$ which  /usr/local/bin/pdftoppm 
/usr/local/bin/pdftoppm
$ pkg which /usr/local/bin/pdftoppm
/usr/local/bin/pdftoppm was installed by package poppler-utils-0.77.0
```

**Comment by yurivict** [comment]
there is some file path in place of period in the code. When this argument is empty, it works. You should just remove it because ```-jpeg``` doesn't accept arguments.

**Comment by mananapr** [comment]
I tried the following command

>pdftoppm -l 1 -jpeg lainzine03.pdf -singlefile /tmp/prev

and it's still working for me. you have included an `x.pdf` at the start as well so try removing that?

**Comment by yurivict** [comment]
I've created the FreeBSD port for ```cfiles``` and it is failing to show image and pdf previews. I didn't change any command line elements.

**Comment by yurivict** [comment]
```w3m``` is used.
/tmp/prev.jpg doesn't exist.

**Comment by yurivict** [comment]
You can install FreeBSD in a VM using https://download.freebsd.org/ftp/releases/amd64/amd64/ISO-IMAGES/12.0/FreeBSD-12.0-RELEASE-amd64-disc1.iso

```pkg install subversion``` would install subversion.
Then ```svn checkout https://svn.FreeBSD.org/ports/head /usr/ports``` would check out the latest ports tree.
Then ```/usr/ports/deskutils/cfiles && make install``` would install ```cfiles```.

**Comment by mananapr** [comment]
To save time I downloaded a vbox image from osboxes that had FreeBSD 12 pre-installed.
Firstly, `pdftoppm` seems to be working fine as shown by [this](https://files.catbox.moe/swk6w9.png) screenshot.

The problem is with the `displayimg` and `clearimg` scripts. There are 2 things you'll have to do to fix that:
1.) FreeBSD install `w3mimgdisplay` at `/usr/local/libexec/w3m/w3mimgdisplay` but both the scripts look for it at `/usr/lib/w3m/w3mimgdisplay` so you'll have to change that.
2.) The other issue is that the scripts have the shebang `#!/bin/bash` but FreeBSD installs bash at `/usr/local/bin/bash`.

After fixing these two issues I was able to get image and pdf previews to work as shown [here](https://files.catbox.moe/wml1o9.png) and [here](https://files.catbox.moe/xk6zc2.png)

If you still encounter any issues let me know and feel free to re-open this issue or make a new one

**Comment by yurivict** [comment]
Where did you see these problems?
The port corrects all of them, and image and pdf preview are still not working.

```
$ cat /usr/local/share/cfiles/scripts/clearimg
#!/usr/local/bin/bash

W3MIMGDISPLAY="/usr/local/libexec/w3m/w3mimgdisplay"
FONTH=8 # Size of one terminal row
FONTW=6 # Size of one terminal column

X=$1
Y=$2
COLUMNS=$3
LINES=$4

x=$((FONTW * X))
y=$((FONTH * Y))

erase="6;$x;$((y-8));$(( FONTW*COLUMNS ));$(( FONTH*LINES ))\n3;"
echo -e "$erase" | $W3MIMGDISPLAY
```

**Comment by mananapr** [comment]
are you also patching `config.h` to use the `displayimg` script? because by default it uses the `displayimg_uberzug` script
