### ISSUE TITLE
Error with preview.

### ISSUE THREAD

**Issue by Enigmage** [mananapr/cfiles#52]
Whenever, in the root directory, the lost+found or root folders are highlighted, Cfiles crashes, usually with the error with preview message, so I have to manually press r(reload) to get it to work again properly. It probably has something to do with those two directories as they are not accessible by a non-root user.  Expected behaviour should be to display a not accessible message(or similar) when these directories are highlighted like in ranger, but cfiles just breaks.

Here are some screenshots.

![cfilebug1](https://user-images.githubusercontent.com/53875706/82826639-25ec1500-9ecb-11ea-885c-160cc75a083c.png)
![cfilebug2](https://user-images.githubusercontent.com/53875706/82826866-8aa76f80-9ecb-11ea-8a1f-6d191759d0f0.png)

OS: Pop!_OS 20.04 LTS 
I compiled the app manually from source.

**Comment by mananapr** [comment]
I've fixed it in the most recent commit so you might wanna try that and let me know.
Also thanks for showing interest in `cfiles`. This was my first big project with C so there will a lot of bugs and imperfections. I've pretty much stopped the development because there are a lot of other things going on in my life right now on which I have to focus

**Comment by Enigmage** [comment]
Yes it works great now thanks !!
As for bugs, I haven't found many except this, your work is definitely commendable.
